CREATE DATABASE ESHOPPING_DB;
GO

USE ESHOPPING_DB;
GO

CREATE TABLE NHOMSANPHAM
(
    MaNhom VARCHAR(10) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE SANPHAM
(
    MaSanPham VARCHAR(10) PRIMARY KEY,
    MaNhom VARCHAR(10) NOT NULL,

    TenSanPham NVARCHAR(200) NOT NULL,
    NhaSanXuat NVARCHAR(100),
    HinhAnh NVARCHAR(255),

    GiaBan DECIMAL(18,2) NOT NULL,
    SoLuongTon INT NOT NULL,
    TinhTrang NVARCHAR(50),

    CONSTRAINT FK_SANPHAM_NHOMSANPHAM
        FOREIGN KEY (MaNhom)
        REFERENCES NHOMSANPHAM(MaNhom),

    CONSTRAINT CK_SANPHAM_GIABAN
        CHECK (GiaBan >= 0),

    CONSTRAINT CK_SANPHAM_SOLUONGTON
        CHECK (SoLuongTon >= 0)
);
GO

CREATE TABLE KHACHHANG
(
    MaKhachHang VARCHAR(10) PRIMARY KEY,

    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    DiaChi NVARCHAR(255),
    DienThoai VARCHAR(20),
    Email VARCHAR(100)
);
GO

CREATE TABLE DONHANG
(
    MaDonHang VARCHAR(10) PRIMARY KEY,

    MaKhachHang VARCHAR(10) NOT NULL,

    NgayDat DATETIME NOT NULL
        DEFAULT GETDATE(),

    TrangThai NVARCHAR(50) NOT NULL,

    CONSTRAINT FK_DONHANG_KHACHHANG
        FOREIGN KEY (MaKhachHang)
        REFERENCES KHACHHANG(MaKhachHang)
);
GO

CREATE TABLE CHITIETDONHANG
(
    MaDonHang VARCHAR(10) NOT NULL,
    MaSanPham VARCHAR(10) NOT NULL,

    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_CHITIETDONHANG
        PRIMARY KEY (MaDonHang, MaSanPham),

    CONSTRAINT FK_CTDH_DONHANG
        FOREIGN KEY (MaDonHang)
        REFERENCES DONHANG(MaDonHang),

    CONSTRAINT FK_CTDH_SANPHAM
        FOREIGN KEY (MaSanPham)
        REFERENCES SANPHAM(MaSanPham),

    CONSTRAINT CK_CTDH_SOLUONG
        CHECK (SoLuong > 0),

    CONSTRAINT CK_CTDH_DONGIA
        CHECK (DonGia >= 0)
);
GO

CREATE TABLE THANHTOAN
(
    MaThanhToan VARCHAR(10) PRIMARY KEY,

    MaDonHang VARCHAR(10) NOT NULL,

    TrangThai NVARCHAR(50) NOT NULL,

    ThoiGianThanhToan DATETIME,

    CONSTRAINT FK_THANHTOAN_DONHANG
        FOREIGN KEY (MaDonHang)
        REFERENCES DONHANG(MaDonHang),

    CONSTRAINT UQ_THANHTOAN_DONHANG
        UNIQUE (MaDonHang)
);
GO